// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqizbwfpdcpdpmugmymw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxaXpid2ZwZGNwZHBtdWdteW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NTY2MTgsImV4cCI6MjA3NjEzMjYxOH0.RK9aHkyBheEg47fERT6oAmGsc8J7FgeLvWeQx9QguCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});